### ISSUE TITLE
Add Fragments

### ISSUE THREAD

**Issue by hiteshgarg002** [Devlight/NavigationTabBar#107]
How can i add fragments? i have tried everything i could but failed to add fragments.

**Comment by palafix** [comment]
I have make it like this and it works.

 private void initUI() {
        final ViewPager pager = (ViewPager) findViewById(R.id.view_space);
        pager.setAdapter(new FragmentPagerAdapter(getSupportFragmentManager()) {
            // Returns total number of pages
            @Override
            public int getCount() {
                return 5;
            }

            // Returns the fragment to display for that page
            @Override
            public Fragment getItem(int position) {
                switch (position) {
                    case 0: // Fragment # 0 - This will show FirstFragment

                        return new News();
                    case 1: // Fragment # 1 - This will show SecondFragment

                        return new Friends();
                    case 2: // Fragment # 2 - This will show ThirdFragment

                        return new Mess();
                    case 3: // Fragment # 3 - This will show FourthFragment

                        return new Notification();
                    case 4: // Fragment # 4 - This will show FifthFragment

                        return new Menufb();
                    default:
                        return new News();
                }
            }

            // Returns the page title for the top indicator
            @Override
            public CharSequence getPageTitle(int position) {
                return "Page" + position;
            }

        });
And for back press in mainactivity i use this

if (pager.getCurrentItem() != 0) {
                pager.setCurrentItem(pager.getCurrentItem() - 4, true);
                return;
            }

**Comment by snajdovski** [comment]
@palafix could you tell in details how you did it I get errors that pager is not declared and some other errors.
