### ISSUE TITLE
Unable to change background color of unselected button

### ISSUE THREAD

**Issue by kumarkeviv** [Devlight/NavigationTabBar#80]
Hi

I am trying to change the color of the un-selected button of Tab Bar, but no matter what it remains black.

Here is the layout parameters i set:

```
 <devlight.io.library.ntb.NavigationTabBar
        android:id="@+id/ntb_horizontal"
        app:ntb_badge_gravity="top"
        app:ntb_badge_position="right"
        app:ntb_badged="true"
        app:ntb_scaled="true"
        app:ntb_swiped="true"
        app:ntb_tinted="true"
        app:ntb_bg_color="@color/colorAccent"
        android:layout_width="match_parent"
        android:layout_height="60dp" />
```

I tried "app:ntb_bg_color" but its not working. Please help.

Here is the screenshot for better view.
![screenshot_2016-12-20-23-56-25](https://cloud.githubusercontent.com/assets/17118240/21363852/46f4e1c4-c714-11e6-9124-478b776f1960.png)

**Comment by ChekistNSK** [comment]
navigationTabBar.setInactiveColor(Color.parseColor("#FFFFFF"));

**Comment by hsnInfinity** [comment]
too late , but i think because in your java class u use 
`navigationTabBar.setBgColor(Color.BLACK)`
